version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5200:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 